//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPassport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public string Name { get; set; }
        public string Official_Name { get; set; }
        public string Continent { get; set; }
        public string Capital { get; set; }
        public string Largest_City { get; set; }
        public string Most_Spoken_Language { get; set; }
        public string Demonym { get; set; }
        public string HoS_Title { get; set; }
        public string Head_of_State { get; set; }
        public string HoS_Picture { get; set; }
        public string HoG_Title { get; set; }
        public string Head_of_Government { get; set; }
        public string HoG_Picture { get; set; }
        public double Population { get; set; }
        public string Currency { get; set; }
        public string Anthem { get; set; }
        public string AnthemHtml { get; set; }
        public string Globe { get; set; }
        public string Flag { get; set; }
        public string CoA { get; set; }
        public string Acceptables { get; set; }
    }
}
